### ISSUE TITLE
 Problem 1

### ISSUE THREAD

**Issue by hyandigit** [devpark/laravel-przelewy24#14]
Problem 1
    - Root composer.json requires devpark/laravel-przelewy24 1.0.5 -> satisfiable by devpark/laravel-przelewy24[v1.0.5].
    - devpark/laravel-przelewy24 v1.0.5 requires laravel/framework 5.* -> found laravel/framework[v5.0.0, ..., 5.8.x-dev] but it conflicts with your root composer.json require (^6.2).

**Comment by Dartui** [comment]
Try changing you dependency from something like `"devpark/laravel-przelewy24": "^1.0"` to `"devpark/laravel-przelewy24": "dev-master"`.

There is no tagged version with support for Laravel 6.x and 7.x, but there are changes on master branch.

**Comment by kamilloo** [comment]
Published release v1.0.6  `Support Laravel v6, v7, v8`
