### ISSUE TITLE
Update guzzlehttp/guzzle

### ISSUE THREAD

**Issue by wvffle** [devpark/laravel-przelewy24#15]
I can't install this package with composer. My project is using laravel 8 and guzzlehttp/guzzle ^7.2.

It's says there's a conflict with this package as it uses ^6.2

**Comment by kamilloo** [comment]
@wvffle 
new version released
please upgrade to v3.0

**Comment by wvffle** [comment]
Thanks for info! I don't have time to update that project now, though I believe you've resolved the issue ;p
