### ISSUE TITLE
Sample code

### ISSUE THREAD

**Issue by Kkiomen** [devpark/laravel-przelewy24#26]
Could you please add sample codes?
I have a problem because the transfer to the Przelewy24 website does not work. It would be nice if there was sample code (sample subpage), which supports this so that you can rebuild it and know that it works

And...

What mean: Add flag force to alter configuration after upgrade package
How can I do it?

**Comment by kamilDevpark** [comment]
Hi @Kkiomen, 

The package, for work, requires Przelewy24 credentials. 
The Payment provider allows using sandbox which our package support.
If the Przelewy24 provider (both live and sandbox) is down, there is no a place to test the real app.
All the package features are covered by tests where the payment partner endpoints are mocked.

There is no prediction to create the extra mocking payment provider by Devpark.

And...

### Add flag force to alter configuration after upgrade package 
means:
From Laravel Doc: 
You will need to overwrite the assets every time the package is updated, you may use the --force flag:

`php artisan vendor:publish --provider="Devpark\Transfers24\Providers\Transfers24ServiceProvider" --force`
