### ISSUE TITLE
Błąd 

### ISSUE THREAD

**Issue by KonradMil** [devpark/laravel-przelewy24#28]
Obecnie jako potwierdzenie transakcji Przelewy24 wysyła orderID jako int nie jako string, który jest wymagany przez paczkę.
Wywala to po cichu przyjmowanie transakcji na metodzie verify.

**Comment by ghost** [comment]
@KonradMil Udało Ci się rozwiązać problem?

**Comment by kamilloo** [comment]
@KonradMil  fixed #30
