### ISSUE TITLE
Problem z potwierdzeniem statusu

### ISSUE THREAD

**Issue by ghost** [devpark/laravel-przelewy24#29]
Witam,
Mam problem z potwierdzeniem statusu transakcji. Wykorzystałem po części kod z readme:
``
public function status(Request $request) 
    {
            //Log::info($request);
            $payment_verify = app()->make(\Devpark\Transfers24\Requests\Transfers24::class);
            $payment_response = $payment_verify->receive($request);

            if ($payment_response->isSuccess()) {
                ....
}
``
Ale nie chodzi mi poniżej ->isSuccess(). Wie ktoś może co może być powodem? $request przychodzi poprawny z przelewy24....

**Comment by kamilloo** [comment]
fixed #30
