### ISSUE TITLE
Problem z statusem

### ISSUE THREAD

**Issue by majweb** [devpark/laravel-przelewy24#31]
Realizuje płatność i mam metodę status z przykładu readme i nie wykonuje jej. Dałem Loga na początek czy wogole do niej wchodzi. Okazuje się że nie co jest nie tak? Próbowałem lokalnie i na produkcji ten sam problem.

**Comment by Kkiomen** [comment]
Mam ten sam problem

**Comment by kamilloo** [comment]
Witam
Czy instalujesz paczkę poraz pierwszy czy jedynie podnosisz wersję?
pozdrawiam
Kamil Piętka

czw., 7 kwi 2022 o 16:57 Marcin Maj ***@***.***> napisał(a):

**Comment by kamilloo** [comment]
@majweb too less info to continue issue
