### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by Adasqu** [devpark/laravel-przelewy24#32]
After switch from sandbox to prod I have this message(CRC, report changed):
Client error: `POST https://secure.przelewy24.pl/api/v1/transaction/register` resulted in a `401 Unauthorized` response:
{"error":"Incorrect authentication","code":401}

**Comment by kamilloo** [comment]
@Adasqu , was the problem issue later, more than once?

**Comment by krychu90** [comment]
I had this message in v3 on production when my account was not fully activated. On v1 I got proper message.

**Comment by kamilloo** [comment]
v3 version is currently supported,  please use v3 on production ith fully activated account
